--------------------------------------------------------
--  File created - �ѹ�����-�ѹ��¹-28-2567   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACCESSROOM
--------------------------------------------------------

  CREATE TABLE "ACCESSROOM" 
   (	"ACCESSID" VARCHAR2(10 BYTE), 
	"ACCESSDATE" DATE, 
	"ACCESS_EMPID" VARCHAR2(10 BYTE), 
	"ACCESS_RESERVEID" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BUILDING
--------------------------------------------------------

  CREATE TABLE "BUILDING" 
   (	"BUIID" VARCHAR2(10 BYTE), 
	"BUINAME" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPARTMENT
--------------------------------------------------------

  CREATE TABLE "DEPARTMENT" 
   (	"DEPID" VARCHAR2(10 BYTE), 
	"DEPNAME" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DURATION
--------------------------------------------------------

  CREATE TABLE "DURATION" 
   (	"DURATIONID" VARCHAR2(10 BYTE), 
	"DURATIONSTARTTIME" TIMESTAMP (6), 
	"DURATIONENDTIME" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "EMPLOYEE" 
   (	"EMPID" VARCHAR2(10 BYTE), 
	"EMPFNAME" VARCHAR2(50 BYTE), 
	"EMPLNAME" VARCHAR2(50 BYTE), 
	"EMPUSERNAME" VARCHAR2(50 BYTE), 
	"EMPPASSWORD" VARCHAR2(50 BYTE), 
	"EMPGENDER" VARCHAR2(1 BYTE), 
	"EMPBDATE" DATE, 
	"EMPPHONE" VARCHAR2(10 BYTE), 
	"EMPCOUNTLOCK" NUMBER(*,0), 
	"EMP_DEPID" VARCHAR2(10 BYTE), 
	"EMP_ROLEID" VARCHAR2(10 BYTE), 
	"EMP_STALD" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FLOOR
--------------------------------------------------------

  CREATE TABLE "FLOOR" 
   (	"FLOORID" VARCHAR2(10 BYTE), 
	"FLOORNAME" VARCHAR2(2 BYTE), 
	"BUIID" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOCK_TABLE
--------------------------------------------------------

  CREATE TABLE "LOCK_TABLE" 
   (	"LOCKID" VARCHAR2(10 BYTE), 
	"LOCKDATE" DATE, 
	"LOCK_EMPID" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RESERVEIDTAILCANCEL
--------------------------------------------------------

  CREATE TABLE "RESERVEIDTAILCANCEL" 
   (	"DETAIL_TEXT" VARCHAR2(255 BYTE), 
	"RDC_RESERVEID" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RESERVEROOM
--------------------------------------------------------

  CREATE TABLE "RESERVEROOM" 
   (	"RESERVEID" VARCHAR2(10 BYTE), 
	"RESERVELWILLDATE" DATE, 
	"RESERVELDETAIL" VARCHAR2(255 BYTE), 
	"RESERVELQRCODE" VARCHAR2(255 BYTE), 
	"RESERVEL_EMPID" VARCHAR2(10 BYTE), 
	"RESERVEL_DURATIONID" VARCHAR2(10 BYTE), 
	"RESERVEL_ROOMID" VARCHAR2(10 BYTE), 
	"RESERVEL_STAID" VARCHAR2(10 BYTE), 
	"RESERVEL_BOOKINGSTATUSID" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROLE
--------------------------------------------------------

  CREATE TABLE "ROLE" 
   (	"ROLEID" VARCHAR2(10 BYTE), 
	"ROLENAME" VARCHAR2(50 BYTE), 
	"ROLEACCESS" VARCHAR2(100 BYTE), 
	"ROLE_STAID" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROOM
--------------------------------------------------------

  CREATE TABLE "ROOM" 
   (	"ROOMID" VARCHAR2(10 BYTE), 
	"ROOMNAME" VARCHAR2(20 BYTE), 
	"ROOMCAPACITY" NUMBER(*,0), 
	"ROOMDETAIL" VARCHAR2(255 BYTE), 
	"ROOM_FLOORID" VARCHAR2(10 BYTE), 
	"ROOM_ROOMTYPTID" VARCHAR2(10 BYTE), 
	"ROOM_STAID" VARCHAR2(10 BYTE), 
	"ROOM_EMPID" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROOMTYPT
--------------------------------------------------------

  CREATE TABLE "ROOMTYPT" 
   (	"ROOMTYPTID" VARCHAR2(10 BYTE), 
	"ROOMTYPNAME" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STATUS
--------------------------------------------------------

  CREATE TABLE "STATUS" 
   (	"STAID" VARCHAR2(10 BYTE), 
	"STANAME" VARCHAR2(50 BYTE), 
	"STA_STATYPID" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STATUSTYPE
--------------------------------------------------------

  CREATE TABLE "STATUSTYPE" 
   (	"STATYPID" VARCHAR2(10 BYTE), 
	"STATYPNAME" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ACCESSROOM
SET DEFINE OFF;
REM INSERTING into BUILDING
SET DEFINE OFF;
Insert into BUILDING (BUIID,BUINAME) values ('BUI0000001','MIIX');
Insert into BUILDING (BUIID,BUINAME) values ('BUI0000002','MII');
Insert into BUILDING (BUIID,BUINAME) values ('BUD0000003','A');
Insert into BUILDING (BUIID,BUINAME) values ('BUD0000004','D');
Insert into BUILDING (BUIID,BUINAME) values ('BUD0000005','E');
Insert into BUILDING (BUIID,BUINAME) values ('BUD0000006','F');
REM INSERTING into DEPARTMENT
SET DEFINE OFF;
Insert into DEPARTMENT (DEPID,DEPNAME) values ('DEP0000001','�ҹ����¹');
Insert into DEPARTMENT (DEPID,DEPNAME) values ('DEP0000002','�����ø�áԨ');
REM INSERTING into DURATION
SET DEFINE OFF;
Insert into DURATION (DURATIONID,DURATIONSTARTTIME,DURATIONENDTIME) values ('DOR0000001',to_timestamp('27 �.�.  2024 09.00.00.000000000','DD MON RRRR HH24.MI.SSXFF'),to_timestamp('27 �.�.  2024 11.30.00.000000000','DD MON RRRR HH24.MI.SSXFF'));
Insert into DURATION (DURATIONID,DURATIONSTARTTIME,DURATIONENDTIME) values ('DOR0000002',to_timestamp('28 �.�.  2024 12.30.00.000000000','DD MON RRRR HH24.MI.SSXFF'),to_timestamp('28 �.�.  2024 15.00.00.000000000','DD MON RRRR HH24.MI.SSXFF'));
REM INSERTING into EMPLOYEE
SET DEFINE OFF;
Insert into EMPLOYEE (EMPID,EMPFNAME,EMPLNAME,EMPUSERNAME,EMPPASSWORD,EMPGENDER,EMPBDATE,EMPPHONE,EMPCOUNTLOCK,EMP_DEPID,EMP_ROLEID,EMP_STALD) values ('EMP0000002','Somying','Boondee','Somying','7110eda4d09e062aa5e4a390b0a572ac0d2c0220','F',to_date('14 ��.�. 2024','DD MON RRRR'),'9876543210',0,'DEP0000001','ROL0000001','STA0000001');
Insert into EMPLOYEE (EMPID,EMPFNAME,EMPLNAME,EMPUSERNAME,EMPPASSWORD,EMPGENDER,EMPBDATE,EMPPHONE,EMPCOUNTLOCK,EMP_DEPID,EMP_ROLEID,EMP_STALD) values ('EMP0000001','��ʹ��','������','admin','7110eda4d09e062aa5e4a390b0a572ac0d2c0220','M',to_date('04 �.�.  2019','DD MON RRRR'),'0980300822',0,'DEP0000001','ROL0000001','STA0000001');
Insert into EMPLOYEE (EMPID,EMPFNAME,EMPLNAME,EMPUSERNAME,EMPPASSWORD,EMPGENDER,EMPBDATE,EMPPHONE,EMPCOUNTLOCK,EMP_DEPID,EMP_ROLEID,EMP_STALD) values ('EMP0000003','�Ѫ�ҹ���','׷Ծºح���','EMP0000003','011c945f30ce2cbafc452f39840f025693339c42','M',to_date('01 �.�.  2013','DD MON RRRR'),'0980300822',0,'DEP0000001','ROL0000003','STA0000001');
REM INSERTING into FLOOR
SET DEFINE OFF;
Insert into FLOOR (FLOORID,FLOORNAME,BUIID) values ('FLO0000001','1','BUI0000001');
Insert into FLOOR (FLOORID,FLOORNAME,BUIID) values ('FLO0000002','2','BUI0000001');
Insert into FLOOR (FLOORID,FLOORNAME,BUIID) values ('FLO0000003','3','BUI0000001');
Insert into FLOOR (FLOORID,FLOORNAME,BUIID) values ('FLO0000004','1','BUI0000002');
Insert into FLOOR (FLOORID,FLOORNAME,BUIID) values ('FLO0000005','2','BUI0000002');
REM INSERTING into LOCK_TABLE
SET DEFINE OFF;
REM INSERTING into RESERVEIDTAILCANCEL
SET DEFINE OFF;
REM INSERTING into RESERVEROOM
SET DEFINE OFF;
Insert into RESERVEROOM (RESERVEID,RESERVELWILLDATE,RESERVELDETAIL,RESERVELQRCODE,RESERVEL_EMPID,RESERVEL_DURATIONID,RESERVEL_ROOMID,RESERVEL_STAID,RESERVEL_BOOKINGSTATUSID) values ('RES0000001',to_date('02 �.�.  2024','DD MON RRRR'),'����������','212345','EMP0000001','DOR0000001','ROM0000001','STA0000005','STA0000007');
Insert into RESERVEROOM (RESERVEID,RESERVELWILLDATE,RESERVELDETAIL,RESERVELQRCODE,RESERVEL_EMPID,RESERVEL_DURATIONID,RESERVEL_ROOMID,RESERVEL_STAID,RESERVEL_BOOKINGSTATUSID) values ('RES0000002',to_date('02 �.�.  2024','DD MON RRRR'),'����','1541654654','EMP0000001','DOR0000002','ROM0000001','STA0000005','STA0000007');
REM INSERTING into ROLE
SET DEFINE OFF;
Insert into ROLE (ROLEID,ROLENAME,ROLEACCESS,ROLE_STAID) values ('ROL0000002','�����ҹ','1111111000','STA0000003');
Insert into ROLE (ROLEID,ROLENAME,ROLEACCESS,ROLE_STAID) values ('ROL0000003','��ѡ�ҹ','1111000011','STA0000003');
Insert into ROLE (ROLEID,ROLENAME,ROLEACCESS,ROLE_STAID) values ('ROL0000001','�������к�','1111111111','STA0000003');
REM INSERTING into ROOM
SET DEFINE OFF;
Insert into ROOM (ROOMID,ROOMNAME,ROOMCAPACITY,ROOMDETAIL,ROOM_FLOORID,ROOM_ROOMTYPTID,ROOM_STAID,ROOM_EMPID) values ('ROM0000001','MII101',60,'��ਤ���� 2 ���','FLO0000001','RTY0000001','STA0000003','EMP0000001');
REM INSERTING into ROOMTYPT
SET DEFINE OFF;
Insert into ROOMTYPT (ROOMTYPTID,ROOMTYPNAME) values ('RTY0000001','VIP');
Insert into ROOMTYPT (ROOMTYPTID,ROOMTYPNAME) values ('RTY0000002','�����');
REM INSERTING into STATUS
SET DEFINE OFF;
Insert into STATUS (STAID,STANAME,STA_STATYPID) values ('STA0000005','͹��ѵ�','STT0000003');
Insert into STATUS (STAID,STANAME,STA_STATYPID) values ('STA0000006','���͹��ѵ�','STT0000003');
Insert into STATUS (STAID,STANAME,STA_STATYPID) values ('STA0000007','�ͧ','STT0000004');
Insert into STATUS (STAID,STANAME,STA_STATYPID) values ('STA0000008','¡��ԡ��èͧ','STT0000004');
Insert into STATUS (STAID,STANAME,STA_STATYPID) values ('STA0000001','��Ժѵԧҹ','STT0000001');
Insert into STATUS (STAID,STANAME,STA_STATYPID) values ('STA0000002','����ش��û�Ժѵԧҹ','STT0000001');
Insert into STATUS (STAID,STANAME,STA_STATYPID) values ('STA0000003','��ҹ','STT0000002');
Insert into STATUS (STAID,STANAME,STA_STATYPID) values ('STA0000004','�����ҹ','STT0000002');
REM INSERTING into STATUSTYPE
SET DEFINE OFF;
Insert into STATUSTYPE (STATYPID,STATYPNAME) values ('STT0000003','���͹��ѵ�');
Insert into STATUSTYPE (STATYPID,STATYPNAME) values ('STT0000004','��èͧ');
Insert into STATUSTYPE (STATYPID,STATYPNAME) values ('STT0000001','��Ժѵԧҹ');
Insert into STATUSTYPE (STATYPID,STATYPNAME) values ('STT0000002','�����ҹ');
--------------------------------------------------------
--  DDL for Index IDX_ACCESS_RESERVEID
--------------------------------------------------------

  CREATE INDEX "IDX_ACCESS_RESERVEID" ON "ACCESSROOM" ("ACCESS_RESERVEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_ACCESS_EMPID
--------------------------------------------------------

  CREATE INDEX "IDX_ACCESS_EMPID" ON "ACCESSROOM" ("ACCESS_EMPID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BUILDING
--------------------------------------------------------

  ALTER TABLE "BUILDING" MODIFY ("BUIID" NOT NULL ENABLE);
 
  ALTER TABLE "BUILDING" MODIFY ("BUINAME" NOT NULL ENABLE);
 
  ALTER TABLE "BUILDING" ADD PRIMARY KEY ("BUIID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROLE
--------------------------------------------------------

  ALTER TABLE "ROLE" MODIFY ("ROLEID" NOT NULL ENABLE);
 
  ALTER TABLE "ROLE" MODIFY ("ROLENAME" NOT NULL ENABLE);
 
  ALTER TABLE "ROLE" MODIFY ("ROLEACCESS" NOT NULL ENABLE);
 
  ALTER TABLE "ROLE" MODIFY ("ROLE_STAID" NOT NULL ENABLE);
 
  ALTER TABLE "ROLE" ADD PRIMARY KEY ("ROLEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESERVEIDTAILCANCEL
--------------------------------------------------------

  ALTER TABLE "RESERVEIDTAILCANCEL" MODIFY ("DETAIL_TEXT" NOT NULL ENABLE);
 
  ALTER TABLE "RESERVEIDTAILCANCEL" MODIFY ("RDC_RESERVEID" NOT NULL ENABLE);
 
  ALTER TABLE "RESERVEIDTAILCANCEL" ADD PRIMARY KEY ("RDC_RESERVEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOCK_TABLE
--------------------------------------------------------

  ALTER TABLE "LOCK_TABLE" MODIFY ("LOCKID" NOT NULL ENABLE);
 
  ALTER TABLE "LOCK_TABLE" MODIFY ("LOCKDATE" NOT NULL ENABLE);
 
  ALTER TABLE "LOCK_TABLE" MODIFY ("LOCK_EMPID" NOT NULL ENABLE);
 
  ALTER TABLE "LOCK_TABLE" ADD PRIMARY KEY ("LOCKID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACCESSROOM
--------------------------------------------------------

  ALTER TABLE "ACCESSROOM" MODIFY ("ACCESSID" NOT NULL ENABLE);
 
  ALTER TABLE "ACCESSROOM" MODIFY ("ACCESSDATE" NOT NULL ENABLE);
 
  ALTER TABLE "ACCESSROOM" MODIFY ("ACCESS_EMPID" NOT NULL ENABLE);
 
  ALTER TABLE "ACCESSROOM" MODIFY ("ACCESS_RESERVEID" NOT NULL ENABLE);
 
  ALTER TABLE "ACCESSROOM" ADD PRIMARY KEY ("ACCESSID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FLOOR
--------------------------------------------------------

  ALTER TABLE "FLOOR" MODIFY ("FLOORID" NOT NULL ENABLE);
 
  ALTER TABLE "FLOOR" MODIFY ("FLOORNAME" NOT NULL ENABLE);
 
  ALTER TABLE "FLOOR" MODIFY ("BUIID" NOT NULL ENABLE);
 
  ALTER TABLE "FLOOR" ADD PRIMARY KEY ("FLOORID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESERVEROOM
--------------------------------------------------------

  ALTER TABLE "RESERVEROOM" MODIFY ("RESERVEID" NOT NULL ENABLE);
 
  ALTER TABLE "RESERVEROOM" MODIFY ("RESERVELWILLDATE" NOT NULL ENABLE);
 
  ALTER TABLE "RESERVEROOM" MODIFY ("RESERVELDETAIL" NOT NULL ENABLE);
 
  ALTER TABLE "RESERVEROOM" MODIFY ("RESERVELQRCODE" NOT NULL ENABLE);
 
  ALTER TABLE "RESERVEROOM" MODIFY ("RESERVEL_EMPID" NOT NULL ENABLE);
 
  ALTER TABLE "RESERVEROOM" MODIFY ("RESERVEL_DURATIONID" NOT NULL ENABLE);
 
  ALTER TABLE "RESERVEROOM" MODIFY ("RESERVEL_ROOMID" NOT NULL ENABLE);
 
  ALTER TABLE "RESERVEROOM" MODIFY ("RESERVEL_STAID" NOT NULL ENABLE);
 
  ALTER TABLE "RESERVEROOM" MODIFY ("RESERVEL_BOOKINGSTATUSID" NOT NULL ENABLE);
 
  ALTER TABLE "RESERVEROOM" ADD PRIMARY KEY ("RESERVEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPARTMENT
--------------------------------------------------------

  ALTER TABLE "DEPARTMENT" MODIFY ("DEPID" NOT NULL ENABLE);
 
  ALTER TABLE "DEPARTMENT" MODIFY ("DEPNAME" NOT NULL ENABLE);
 
  ALTER TABLE "DEPARTMENT" ADD PRIMARY KEY ("DEPID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STATUSTYPE
--------------------------------------------------------

  ALTER TABLE "STATUSTYPE" MODIFY ("STATYPID" NOT NULL ENABLE);
 
  ALTER TABLE "STATUSTYPE" MODIFY ("STATYPNAME" NOT NULL ENABLE);
 
  ALTER TABLE "STATUSTYPE" ADD PRIMARY KEY ("STATYPID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROOMTYPT
--------------------------------------------------------

  ALTER TABLE "ROOMTYPT" MODIFY ("ROOMTYPTID" NOT NULL ENABLE);
 
  ALTER TABLE "ROOMTYPT" MODIFY ("ROOMTYPNAME" NOT NULL ENABLE);
 
  ALTER TABLE "ROOMTYPT" ADD PRIMARY KEY ("ROOMTYPTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DURATION
--------------------------------------------------------

  ALTER TABLE "DURATION" MODIFY ("DURATIONID" NOT NULL ENABLE);
 
  ALTER TABLE "DURATION" MODIFY ("DURATIONSTARTTIME" NOT NULL ENABLE);
 
  ALTER TABLE "DURATION" MODIFY ("DURATIONENDTIME" NOT NULL ENABLE);
 
  ALTER TABLE "DURATION" ADD PRIMARY KEY ("DURATIONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "EMPLOYEE" MODIFY ("EMPID" NOT NULL ENABLE);
 
  ALTER TABLE "EMPLOYEE" MODIFY ("EMPFNAME" NOT NULL ENABLE);
 
  ALTER TABLE "EMPLOYEE" MODIFY ("EMPLNAME" NOT NULL ENABLE);
 
  ALTER TABLE "EMPLOYEE" MODIFY ("EMPUSERNAME" NOT NULL ENABLE);
 
  ALTER TABLE "EMPLOYEE" MODIFY ("EMPPASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "EMPLOYEE" MODIFY ("EMPGENDER" NOT NULL ENABLE);
 
  ALTER TABLE "EMPLOYEE" MODIFY ("EMPBDATE" NOT NULL ENABLE);
 
  ALTER TABLE "EMPLOYEE" MODIFY ("EMPPHONE" NOT NULL ENABLE);
 
  ALTER TABLE "EMPLOYEE" MODIFY ("EMPCOUNTLOCK" NOT NULL ENABLE);
 
  ALTER TABLE "EMPLOYEE" MODIFY ("EMP_DEPID" NOT NULL ENABLE);
 
  ALTER TABLE "EMPLOYEE" MODIFY ("EMP_ROLEID" NOT NULL ENABLE);
 
  ALTER TABLE "EMPLOYEE" MODIFY ("EMP_STALD" NOT NULL ENABLE);
 
  ALTER TABLE "EMPLOYEE" ADD PRIMARY KEY ("EMPID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROOM
--------------------------------------------------------

  ALTER TABLE "ROOM" MODIFY ("ROOMID" NOT NULL ENABLE);
 
  ALTER TABLE "ROOM" MODIFY ("ROOMNAME" NOT NULL ENABLE);
 
  ALTER TABLE "ROOM" MODIFY ("ROOMCAPACITY" NOT NULL ENABLE);
 
  ALTER TABLE "ROOM" MODIFY ("ROOMDETAIL" NOT NULL ENABLE);
 
  ALTER TABLE "ROOM" MODIFY ("ROOM_FLOORID" NOT NULL ENABLE);
 
  ALTER TABLE "ROOM" MODIFY ("ROOM_ROOMTYPTID" NOT NULL ENABLE);
 
  ALTER TABLE "ROOM" MODIFY ("ROOM_STAID" NOT NULL ENABLE);
 
  ALTER TABLE "ROOM" ADD PRIMARY KEY ("ROOMID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ROOM" MODIFY ("ROOM_EMPID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STATUS
--------------------------------------------------------

  ALTER TABLE "STATUS" MODIFY ("STAID" NOT NULL ENABLE);
 
  ALTER TABLE "STATUS" MODIFY ("STANAME" NOT NULL ENABLE);
 
  ALTER TABLE "STATUS" MODIFY ("STA_STATYPID" NOT NULL ENABLE);
 
  ALTER TABLE "STATUS" ADD PRIMARY KEY ("STAID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACCESSROOM
--------------------------------------------------------

  ALTER TABLE "ACCESSROOM" ADD CONSTRAINT "FK_ACCESS_EMPID" FOREIGN KEY ("ACCESS_EMPID")
	  REFERENCES "EMPLOYEE" ("EMPID") ENABLE;
 
  ALTER TABLE "ACCESSROOM" ADD CONSTRAINT "FK_ACCESS_RESERVEID" FOREIGN KEY ("ACCESS_RESERVEID")
	  REFERENCES "RESERVEROOM" ("RESERVEID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "FK_DEPARTMENT_DEPID" FOREIGN KEY ("EMP_DEPID")
	  REFERENCES "DEPARTMENT" ("DEPID") ENABLE;
 
  ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "FK_ROLES_ROLEID" FOREIGN KEY ("EMP_ROLEID")
	  REFERENCES "ROLE" ("ROLEID") ENABLE;
 
  ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "FK_STATUS_STAID" FOREIGN KEY ("EMP_STALD")
	  REFERENCES "STATUS" ("STAID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FLOOR
--------------------------------------------------------

  ALTER TABLE "FLOOR" ADD CONSTRAINT "FK_BUILING_BUIID" FOREIGN KEY ("BUIID")
	  REFERENCES "BUILDING" ("BUIID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOCK_TABLE
--------------------------------------------------------

  ALTER TABLE "LOCK_TABLE" ADD CONSTRAINT "FK_LOCK_EMPID" FOREIGN KEY ("LOCK_EMPID")
	  REFERENCES "EMPLOYEE" ("EMPID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESERVEROOM
--------------------------------------------------------

  ALTER TABLE "RESERVEROOM" ADD CONSTRAINT "FK_REDERVEL_DURATION" FOREIGN KEY ("RESERVEL_DURATIONID")
	  REFERENCES "DURATION" ("DURATIONID") ENABLE;
 
  ALTER TABLE "RESERVEROOM" ADD CONSTRAINT "FK_RESERVEL_EMPID" FOREIGN KEY ("RESERVEL_EMPID")
	  REFERENCES "EMPLOYEE" ("EMPID") ENABLE;
 
  ALTER TABLE "RESERVEROOM" ADD CONSTRAINT "FK_RESERVEROOM_BOOKINGSTATUSID" FOREIGN KEY ("RESERVEL_BOOKINGSTATUSID")
	  REFERENCES "STATUS" ("STAID") ENABLE;
 
  ALTER TABLE "RESERVEROOM" ADD CONSTRAINT "FK_RESERVEROOM_STATUS_STAID" FOREIGN KEY ("RESERVEL_STAID")
	  REFERENCES "STATUS" ("STAID") ENABLE;
 
  ALTER TABLE "RESERVEROOM" ADD CONSTRAINT "FK_ROOM_ROOMID" FOREIGN KEY ("RESERVEL_ROOMID")
	  REFERENCES "ROOM" ("ROOMID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ROLE
--------------------------------------------------------

  ALTER TABLE "ROLE" ADD CONSTRAINT "FK_STATUS_STALD" FOREIGN KEY ("ROLE_STAID")
	  REFERENCES "STATUS" ("STAID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ROOM
--------------------------------------------------------

  ALTER TABLE "ROOM" ADD CONSTRAINT "FK_FLOOR_FLOORID" FOREIGN KEY ("ROOM_FLOORID")
	  REFERENCES "FLOOR" ("FLOORID") ENABLE;
 
  ALTER TABLE "ROOM" ADD CONSTRAINT "FK_ROOMTYPT_ROOMTYPTID" FOREIGN KEY ("ROOM_ROOMTYPTID")
	  REFERENCES "ROOMTYPT" ("ROOMTYPTID") ENABLE;
 
  ALTER TABLE "ROOM" ADD CONSTRAINT "FK_ROOM_STATUS_STAID" FOREIGN KEY ("ROOM_STAID")
	  REFERENCES "STATUS" ("STAID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STATUS
--------------------------------------------------------

  ALTER TABLE "STATUS" ADD CONSTRAINT "FK_STATUSTYPE_STATYPID" FOREIGN KEY ("STA_STATYPID")
	  REFERENCES "STATUSTYPE" ("STATYPID") ENABLE;
